### ISSUE TITLE
TypeError: invalid data

### ISSUE THREAD

**Issue by jonaskello** [benoror/better-npm-run#21]
I'm trying to use better-npm-run on Windows but I just get error ```TypeError: invalid data```. To reproduce just copy a short version of the json from the README (btw the json in the README has a trailing comma so it does not work as-is):

```json
{
    "devDependencies": {
        "better-npm-run": "~0.0.1"
    },
  "scripts": {
    "build:dist": "better-npm-run build:dist",
    "test": "better-npm-run test"
  },
  "betterScripts": {
    "build:dist": {
        "command": "webpack --config $npm_package_webpack --progress --colors",
        "env": {
            "NODE_ENV": "development"
        }
    }
  }
}
```

Then run:

```
npm install
npm run build:dist
```

It gives this rather unhelpful output. Is there a way to see the actual problem behind this error?

```
> @ build:dist C:\xxxx\better_test
> better-npm-run build:dist

running better-npm-run in C:\xxx\better_test
Executing script: build:dist

to be executed: webpack --config $npm_package_webpack --progress --colors
net.js:617
    throw new TypeError('invalid data');
    ^

TypeError: invalid data
    at Socket.write (net.js:617:11)
    at ChildProcess.<anonymous> (C:\xxx\better_test\node_modules\better-npm-run\lib\exec.js:32:18)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:dist"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE
npm ERR! @ build:dist: `better-npm-run build:dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:dist script 'better-npm-run build:dist'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run build:dist
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xxxx\better_test\npm-debug.log
```
Also checked npm-debug.log but it has no useful info....

**Comment by jonaskello** [comment]
Also this config works:

```json
{
    "devDependencies": {
        "better-npm-run": "~0.0.1"
    },
  "scripts": {
    "build:dist": "better-npm-run build:dist",
    "test": "better-npm-run test"
  },
  "betterScripts": {
    "build:dist": {
        "command": "echo hello",
        "env": {
            "NODE_ENV": "development"
        }
    }
  }
}
```

But as soon as there is something wrong I just get the unhelpful TypeError as above. 

Here is a simpler config that gives TypeError:

```json
{
    "devDependencies": {
        "better-npm-run": "~0.0.1"
    },
  "scripts": {
    "build:dist": "better-npm-run build:dist",
    "test": "better-npm-run test"
  },
  "betterScripts": {
    "build:dist": {
        "command": "webpack",
        "env": {
            "NODE_ENV": "development"
        }
    }
  }
}
```

I know that ```webpack``` itself works as I can run it OK from the command line.

**Comment by gorangajic** [comment]
is webpack only installed locally ?

**Comment by jonaskello** [comment]
Yes, it is installed with npm install -g webpack.

Maybe a better example is without webpack. If I just try to run a non-existent command I get the same error. Something like this:

```json
{
    "devDependencies": {
        "better-npm-run": "~0.0.1"
    },
  "scripts": {
    "build:dist": "better-npm-run build:dist",
    "test": "better-npm-run test"
  },
  "betterScripts": {
    "build:dist": {
        "command": "doesnotexist",
        "env": {
            "NODE_ENV": "development"
        }
    }
  }
}
```

**Comment by jonaskello** [comment]
Ah, I guess by "installed locally" you mean like this:

```json
{
  "devDependencies": {
    "better-npm-run": "~0.0.1",
    "webpack": "^1.12.4"
  },
  "scripts": {
    "build:dist": "better-npm-run build:dist",
    "test": "better-npm-run test"
  },
  "betterScripts": {
    "build:dist": {
      "command": "webpack",
      "env": {
        "NODE_ENV": "development"
      }
    }
  }
}
```

Still gives the same error though...

**Comment by benoror** [comment]
maybe related to https://github.com/benoror/better-npm-run/issues/5#issuecomment-133504647 ?

**Comment by benoror** [comment]
I will close this issue since there's no new activity.

Feel free to comment if the problem persist and is related to the lib.

**Comment by benoror** [comment]
@jonaskello did you managed to fix it? Someone else is having a similar issue: https://github.com/benoror/better-npm-run/issues/27

**Comment by jonaskello** [comment]
@benoror No sorry. I had some more things that needed to happened in the script so I eventually moved it to shelljs instead.
